# language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.39/hugo_0.39_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    # - pip install Pygments

script:
    - git checkout master
    - rm -rf docs
    - hugo
    - rm -r hugo_0*.deb
    - baseURL=$(cat config.toml | grep baseURL | awk '{print $3}' | tr -d \")
    - echo $baseURL
    - printf $baseURL > docs/CNAME

after_success: 
    - git add --force docs/
    - git -c user.name='travis' -c user.email='travis' commit -m "travis build `date`"
    - githubURL=$(cat config.toml | grep githubURL | awk '{print $3}' | tr -d \")
    - echo $githubURL
    - pushPath=${githubURL/https:*github.com/https://$GH_TOKEN@github.com}
    - echo $pushPath
    - git push $pushPath master
